### ISSUE TITLE
Segmentation fault for large dataset of 5M datapoints of 1024 dimensions

### ISSUE THREAD

**Issue by deepakanand14** [ssarfraz/FINCH-Clustering#26] opened 2022-09-22 11:12 UTC
The segmentation faults occurs at the call of NNDescent function where RP-trees are being built and descent steps are about to start. I am using the H-NNE (https://github.com/koulakis/h-nne/issues/17) algorithm which uses FINCH under the hood.

**Comment by ssarfraz** [comment] 2022-09-23 06:30
Hi , I can't reproduce this on my machine. Looks like it is more related to some s/w or hardware limitations/conflicts on your end.

Since this is related to pynndescent, 
1. make sure that you are using it with numpy version < 1.21. 
2. may be try running it in a clean environment.
3. Could be your machine config e.g. not enough memory etc, try running it on another machine to rule this out.
4. 
Other than that can not help you more here. Since you have opened this issue on h-nne as well I will be closing this here. After checking the above steps, if it resolves the issue please close it on h-nne repo as well.

Thanks

**Closed as not planned** 2022-09-23 08:40 UTC
